### ISSUE TITLE
Error on BAM file created from FASTQ

### ISSUE THREAD

**Issue by hyounesy** [umich-brcf-bioinf/Connor#1]
Hello,
I am trying to use connor to dedup reads tagged with the ThruPLEX tag-seq library. My input is given as two fastq files (paired-end), so I am using FastqToSam in Picard tools to convert the paired-end fastq files into a single BAM:
`java -Xmx8G -jar FastqToSam.jar FASTQ=input1.fastq FASTQ2=input2.fastq OUTPUT=input.bam SAMPLE_NAME=SampleName`
 
I am intentionally not using an aligner to go from FastQ to BAM since I want to remove tags first. 

When I try running connor in the created BAM file, I get the following error:
`connor usage problem: Specified input [input.bam] not a valid BAM. Review inputs and try again.`
Is there a way to find more information about what is wrong with the BAM file? Also, do you have a recommended way of creating proper BAM files for connor? 
Here is the first few lines of the created BAM file:

```
@HD     VN:1.4  SO:queryname
@RG     ID:A    SM:SampleName
M00810:107:000000000-D2CBD:1:1101:10000:10340   77      *       0       0       *       *       0       0       TAGTGCTCAGTAGCTCATTGTTATTGCTATTGTTGGGGTCTTTGTTGATTGTTGTCTGTTTGTTTTTGCTGGGGATTGAACCTAGGGCCTCACACACACTAGGCAAGCTCTCTGTAACTGAGTCACTGAGCTACTGACCTGTA       ABBABFFFFFFFGGGGFGFGGGHGHHHHHHHHHHHHGGEEHHHHHHHHHHHHHAHHHHHHHHHHHHG?3FFBEFFEGGFBFEHFFHEHEAFGHFE?DEEBFGEGHHEHGE4FHFHGHGBFFHDEEGHFF3F33F33EGGFCG3       RG:Z:A
M00810:107:000000000-D2CBD:1:1101:10000:10340   141     *       0       0       *       *       0       0       TACAGGTCAGTAGCTCAGTGACTCAGTTACAGAGAGCTTGCCTAGTGTGTGTGAGGCCCTAGGTTCAATCCCCAGCAAAAACAAACAGACAACAATCAACAAAGACCCCAACAATAGCAATAACAATGAGCTACTGAGCACTA       A?ABBFFFFFFFGGGGGFGGGGFHGHGHHHHFHFFGHHHHHGHHHGFFGCGBGHGGGGGFHHHGFHHHHHHHGGGHGHFHHGHHHGHEGHFHHHHFFHB?GEFGCGFHGGGGGHBFGHFHHHHEHHHFGFGFGGG3FGGBGHH       RG:Z:A
M00810:107:000000000-D2CBD:1:1101:10000:11611   77      *       0       0       *       *       0       0       ACGGCTGTAGCTCAGGAAGAAAGAGATTCAAAGTTATGAAACCTTAGGAAAAAAATAAGCATTACAAGAGGACTAGAAAAATGGTAATATGAAAGAATCAACCATTTAAAAATTCAGTAAAAGAAAAACCCTTAAGATGAATAATGCATAAAGTGC  B@BBBBBFFFFFGGGGGGGGGGHHHHHHGHGHHGHHHHHHHHHHGHHHHHHHHGGGHHHHHHGHHHHHHHHHHHHHHHHGHGHHFGHHHHHHHHHHHHHGHHHGHHHHHHHHHHHHHHHHHHHGHGHHFGGHHHHHHHGGHHGHBGHGHHHHHHHH  RG:Z:A
```

Thank you in advance.

**Comment by hyounesy** [comment]
Ok, never mind. Looks like I do have to align the reads and get a proper BAM file first. The [methods section](../blob/master/doc/METHODS.rst) was pretty informative:

**Comment by cgates** [comment]
Your understanding is correct and I'm glad the methods document helped. Connor does not yet support the workflow where you trim tags prior to deduplication; it is something we are considering for a future release. Also I have made a note to make that particular error message more informative.

Thanks for your interest in Connor and let us know if you have other questions.
Best,
cg
