### ISSUE TITLE
KeyError: None on 144 in samtools.py

### ISSUE THREAD

**Issue by ccario83** [umich-brcf-bioinf/Connor#2]
Line 144 of **samtools.py** throws `KeyError: None` for me. I'm using very downsampled bam files which is likely causing the problem, but perhaps a change from 
```python
included_count = len(family_filter_stats.pop(None))
```
to 
```python
included_count = len(family_filter_stats.pop(None, []))
```
would be appropriate to prevent this error. 

Cheers!

**Comment by cgates** [comment]
Thanks for this!
You are correct that this is a common side-effect of downsampling the BAMs (which results in no deduplication which in turn causes this error). And I've attached your excellent suggestion to the ticket to deal with this more gracefully. I'm hoping to get this fix in soon, but let me know if you are blocked.
Best,
cg

**Comment by cgates** [comment]
Connor v0.5.1 incorporates this fix.
Thanks!
