### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by sebastian-luna-valero** [umich-brcf-bioinf/Connor#3]
Hi,

Have you considered creating a conda package for `connor`?

I am happy to add it to bioconda. Would you be able to assist if I find any issues in the process?

Best regards,
Sebastian

**Comment by cgates** [comment]
Hi Sebastian,

We have considered adding a Conda package, but it's lower down on our roadmap. If you wanted to give it a whirl, I could probably assist with any simple problems. 

Thanks!
cg

**Comment by sebastian-luna-valero** [comment]
Hi Chris,

Great, I have just created an initial version of the recipe:
https://github.com/bioconda/bioconda-recipes/pull/5960

Let's wait for the tests to finish and follow up there.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Hi Chris,

Thanks for your input. `connor` can be already installed with `conda` using the `bioconda` channel. 

It will soon appear in the search website:
http://bioconda.github.io/recipes.html

Best regards,
Sebastian

**Comment by cgates** [comment]
Thank you, Sebastian! I will add this option to our install instructions!
cg

**Comment by sebastian-luna-valero** [comment]
FYI:
http://bioconda.github.io/recipes/connor/README.html

;)
