### ISSUE TITLE
Suggestion: Statistics sorted in output log

### ISSUE THREAD

**Issue by timothee-revil** [umich-brcf-bioinf/Connor#5]
Hi,

It would be great if the statistics (alignments unplaced, etc) were always output in the same order in the log. When comparing multiple logs, it's annoying that the same statistic seems to be randomly placed.

For example, here is one statistic across multiple logs:
![image](https://user-images.githubusercontent.com/8106106/35778051-895cb6f8-0986-11e8-995d-d9feccc844dc.png)

Thanks,
Tim

**Comment by cgates** [comment]
Hi Tim,
That makes total sense, Tim. They are actually sorted, but they are sorted by the amount filtered (i.e. most exclusive filter to least). I will add this as a new feature.
Thanks.
Chris
