### ISSUE TITLE
Suport for TSO500

### ISSUE THREAD

**Issue by drmjc** [umich-brcf-bioinf/Connor#8]
Hi,
I'm using the Illumina TruSight Oncology 500 panel, which uses UMI's. After running Illumina's Basespace bcl2fastq app, the UMI is embedded in the fastq header, rather than the read. example:
@NDX550309_RUO:9:HTCW2BGXB:1:11101:3667:1054:TGTCCGT+NNTGTAT 1:N:0:1
CTATTAGCAAGGNCGTTCCCCNGACTGNTGCCTGCCCCNANAAAACAGATCCTGGCTGTTTCCTNTACAGGCCGAAGNTCAAGCTCGCGACNC
+
EEEEEEEEEEEE#EEEEEEEE#EEEEE#EEEEEEEEEE#E#EEEEEEEEEEEEEEEEEEEEEEE#EEEEEEEEEEEE#EEEEEEEEEEEEE#A

Do you have plans for connor to support this?

Thanks,
Mark

**Comment by cgates** [comment]
Hi Mark,

We worked with Takara to develop Connor as a tool for their ThruPLEX® Tag-seq Kit several years ago. Takara may be also to extend the tool to support a new UMI scheme, but, unfortunately, our group is not resourced to support Connor at this time. I'm sorry we can't help directly, but if you email this request to bfx-connor@umich.edu, it will be forwarded to Takara bioinformatics group and they may be able to help.

FWIW, you might also be interested in UMITools; it is not a "drop-in-replacement" for Connor, but it has some relevant functionality around UMI handling and broader adoption than Connor.

Best,
Chris Gates
